fr:
  title: "Mes services"
  intro: "Que vous soyez un artiste, un collectif ou une marque, je propose une gamme complète de services pour donner vie à votre vision."
  pitch: "Découvrez comment je peux vous aider à créer une **identité visuelle forte** et **cohérente** :"
  generic:
    title: "Besoins ponctuels ?"
    text: "Pour vos <strong>flyers</strong>, <strong>bannières</strong>, <strong>templates réseaux sociaux</strong> ou <strong>retouches urgentes</strong>. <br>Une <strong>solution flexible</strong> pour vos tâches quotidiennes."
    cta: "Me confier une mission"
en:
  title: "My Services"
  intro: "Whether you're an artist, collective, or brand, I offer a comprehensive range of services to bring your vision to life."
  pitch: "Discover how I can help you create a **strong** and **cohesive visual identity** :"
  generic:
    title: "One-off needs?"
    text: "For your <strong>flyers</strong>, <strong>banners</strong>, <strong>social media templates</strong> or <strong>urgent edits</strong>. <br>A <strong>flexible solution</strong> for your day-to-day tasks."
    cta: "Assign me a project"